# netlify.toml
[build]
  command   = "npm run build"
  publish   = "dist"
  functions = "netlify/functions"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_URL,VITE_SUPABASE_ANON_KEY,VITE_STRIPE_PUBLIC_KEY"

# schedule the send-reminders function every day at midnight UTC
[functions.cron]
  send-reminders = "@daily"
